export enum BookingAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  CONFIRMED = 'CONFIRMED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  CANCELLED = 'CANCELLED',
}